import { CellSettings } from '../models';

export const CellSettingsList: CellSettings[] = [
  {
    left: false,
    top: false,
    right: false,
    bottom: false,
    image: 'assets/img/map/unwalkable-cell.svg',
  },
  {
    left: true,
    top: false,
    right: false,
    bottom: false,
    image: 'assets/img/map/left.jpg',
  },
  {
    left: false,
    top: true,
    right: false,
    bottom: false,
    image: 'assets/img/map/top.jpg',
  },
  {
    left: false,
    top: false,
    right: true,
    bottom: false,
    image: 'assets/img/map/right.jpg',
  },
  {
    left: false,
    top: false,
    right: false,
    bottom: true,
    image: 'assets/img/map/bottom.jpg',
  },
  {
    left: true,
    top: false,
    right: true,
    bottom: false,
    image: 'assets/img/map/left-right.jpg',
  },
  {
    left: true,
    top: true,
    right: false,
    bottom: false,
    image: 'assets/img/map/left-top.jpg',
  },
  {
    left: true,
    top: false,
    right: false,
    bottom: true,
    image: 'assets/img/map/left-bottom.jpg',
  },
  {
    left: false,
    top: true,
    right: true,
    bottom: false,
    image: 'assets/img/map/top-right.jpg',
  },
  {
    left: false,
    top: false,
    right: true,
    bottom: true,
    image: 'assets/img/map/right-bottom.jpg',
  },
  {
    left: false,
    top: true,
    right: false,
    bottom: true,
    image: 'assets/img/map/top-bottom.jpg',
  },
  {
    left: true,
    top: true,
    right: true,
    bottom: false,
    image: 'assets/img/map/left-top-right.jpg',
  },
  {
    left: true,
    top: false,
    right: true,
    bottom: true,
    image: 'assets/img/map/left-right-bottom.jpg',
  },
  {
    left: true,
    top: true,
    right: false,
    bottom: true,
    image: 'assets/img/map/left-top-bottom.jpg',
  },
  {
    left: false,
    top: true,
    right: true,
    bottom: true,
    image: 'assets/img/map/top-right-bottom.jpg',
  },
  {
    left: true,
    top: true,
    right: true,
    bottom: true,
    image: 'assets/img/map/all.jpg',
  },
];
